create table dataset (
    id bigint generated always as identity primary key,
    key text not null unique,
    name text not null,
    source text not null,
    start_date date,
    end_date date,
    row_count bigint not null default 0,
    ingested_at timestamptz not null default now(),
    is_reference boolean not null default false
);

create table dataset_column (
    dataset_id bigint not null references dataset (id) on delete cascade,
    column_name text not null,
    non_null_count bigint not null,
    min_value text,
    max_value text,
    is_derived boolean not null default false,
    primary key (dataset_id, column_name)
);

create table baseline (
    metric text not null,
    split text not null default 'all',
    n_players integer not null,
    n_events bigint not null,
    p10 double precision not null,
    p25 double precision not null,
    p50 double precision not null,
    p75 double precision not null,
    p90 double precision not null,
    source_dataset_id bigint not null references dataset (id),
    computed_at timestamptz not null default now(),
    primary key (metric, split)
);

create table pitch (
    id bigint generated always as identity primary key,
    dataset_id bigint not null references dataset (id) on delete cascade,

    game_date date not null,
    game_bam_id bigint not null,
    venue_bam_id bigint,
    venue text,
    league text,
    away_team text,
    home_team text,
    guid text,
    pitch_seq integer not null,
    is_pitch boolean not null,
    is_pickoff boolean not null,
    is_stepoff boolean not null,
    is_pitchout boolean not null,
    is_balk boolean not null,
    terminating boolean not null,
    pitch_code text,
    pitch_result text,
    event_type text,
    description text,
    inning integer not null,
    bottom boolean not null,
    at_bat_number integer not null,
    pre_balls integer not null,
    pre_strikes integer not null,
    pre_outs integer not null,
    pre_basecode text,
    pre_vscore integer,
    pre_hscore integer,
    pre_r1_bam_id bigint,
    pre_r2_bam_id bigint,
    pre_r3_bam_id bigint,
    post_balls integer,
    post_strikes integer,
    post_outs integer,
    post_basecode text,
    post_vscore integer,
    post_hscore integer,
    post_r1_bam_id bigint,
    post_r2_bam_id bigint,
    post_r3_bam_id bigint,
    -- source-file defect: this column holds TRUE/FALSE, not a team id (docs/DATA.md)
    pitcher_team_bam_id boolean,
    pitcher_team text,
    pitcher_bam_id bigint not null,
    pitcher_name_first text,
    pitcher_name_last text,
    pitcher_set text,
    pitcher_side text,
    pitcher_type text,
    batter_team_bam_id bigint,
    batter_team text,
    batter_bam_id bigint not null,
    batter_name_first text,
    batter_name_last text,
    batter_side text not null,
    batter_position integer,
    catcher_bam_id bigint,
    b1_bam_id bigint,
    b2_bam_id bigint,
    b3_bam_id bigint,
    ss_bam_id bigint,
    lf_bam_id bigint,
    cf_bam_id bigint,
    rf_bam_id bigint,
    fielder_position integer,
    fielder_bam_id bigint,
    strikezone_top double precision,
    strikezone_bot double precision,
    pitch_type text,
    rel_speed double precision,
    rel_angle double precision,
    rel_direction double precision,
    rel_side double precision,
    rel_height double precision,
    plate_time double precision,
    spin_axis double precision,
    spin_rate double precision,
    horz_break double precision,
    vert_break double precision,
    induced_vert_break double precision,
    zone_time double precision,
    zone_speed double precision,
    tilt text,
    extension double precision,
    plate_x double precision,
    plate_z double precision,
    hit_trajectory text,
    hit_exit_speed double precision,
    hit_vertical_angle double precision,
    hit_horizontal_angle double precision,
    hit_distance double precision,
    hit_bearing double precision,
    hit_swing_speed double precision,
    hit_contact_x double precision,
    hit_contact_y double precision,
    hit_contact_z double precision,
    vertical_bat_angle double precision,
    horizontal_bat_angle double precision,
    vertical_bat_attack_angle double precision,
    horizontal_bat_attack_angle double precision,
    bat_speed double precision,
    wild_pitch boolean,
    passed_ball boolean,
    in_zone boolean,
    swing boolean not null,
    contact boolean not null,
    in_play boolean not null,
    ball boolean not null,
    called_strike boolean not null,
    swinging_strike boolean not null,
    chase boolean not null,
    foul boolean not null,
    bunt_attempt boolean not null,

    -- derived at ingest, over is_pitch rows only (docs/DESIGN.md)
    pitcher_pitch_no integer,
    times_through_order integer
);

create index pitch_dataset_idx on pitch (dataset_id);
create index pitch_dataset_batter_idx on pitch (dataset_id, batter_bam_id);
